

services:
  app:
# ホストマシン側にデータを永続化するためにvolumesを使う
    volumes:
      - .:/app
  # buildは現在のdirのDockerfileを使ってビルドする
    build:  .
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
      image: postgres
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
