

services:
  app:
# ホストマシン側にデータを永続化するためにvolumesを使う
    volumes:
      - .:/app
  # buildは現在のdirのDockerfileを使ってビルドする
    build:  .
    ports:
      - "8000:8000"
    env_file:
      -  .env
    depends_on:
      db:
        condition: service_heatlthy

  db:
      healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

      image: postgres
      environment:
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_DB: ${POSTGRES_DB}
