"""add transaction_date to transactions

Revision ID: 7ea02b8cbb0c
Revises: 99f4ccb763c0
Create Date: 2026-06-19 06:38:48.995858

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ea02b8cbb0c'
down_revision: Union[str, Sequence[str], None] = '99f4ccb763c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade():
    # 1. まず nullable で追加（既存行はNULLを許す）
    op.add_column('transactions', sa.Column('transaction_date', sa.Date(), nullable=True))
    # 2. 既存行を意味のある値で埋める（例：作成日 created_at の日付部分）
    op.execute("UPDATE transactions SET transaction_date = CAST(created_at AS DATE) WHERE transaction_date IS NULL")

    # 3. 埋め終わってから NOT NULL に変更
    op.alter_column('transactions', 'transaction_date', nullable=False)



def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'transaction_date')
    # ### end Alembic commands ###
